// <auto-generated />
namespace DneWebSite.MigrationsBulltin
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeDatetimeToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeDatetimeToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201605130744391_changeDatetimeToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
