// <auto-generated />
namespace DneWebSite.MigrationsBulltin
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addDcrPlant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDcrPlant));
        
        string IMigrationMetadata.Id
        {
            get { return "201704250157003_addDcrPlant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
